sudo: true

language: node_js

node_js:
- 8
- 7

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso

install:
- export CXX="g++-4.8"
- yarn
- cd app && yarn && cd ..
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 3

script:
- node --version
- yarn lint
- yarn package
- yarn test
- yarn test-e2e

deploy:
  provider: releases
  api_key:
    secure: gB0Lz3xyA9FhDAEpAxO7mv6RkRs0QKKmPJ5lz5CbI5a3QniuPUo0cTlC/w97tiEeF69EfmOJyzmfEY//TlipamD+ivR691UFcWypNHjg1IHJtC3mt6jeiSUqXzlqlmU7otDfz4WtikQgCTjsdorGcJH/QNoN7AQv9tbi4io/kYnCVf5UWbJ3rxBC15zcGCcnrxlROUctW5DF1MM6mXVbJ7t1HZQTwIrQoHgJAEOBJVNLzmY/85uvfDYmVzUzu4AD68vXq6Ry7A8WKSwuEcnXEOxCrDj0lDsmg2Z8OCcfdNhU5ooKlf5VgPJskmmhY37D9PpxIFU/vrHp82ifyNlS5iEp9WmWWryqnNh2YeZu12MtxDac/YLIDTvGpzgwox0CEIHzoy5a4TGBplAsxsILmFjvllksKBv/iRugUNtokIOoWauSnE+jWGbP+8xTa+TkaGzg+vJr3Kt5KuQbQrAEvHCS8TS9eID5RUZznC+bGMA98eMExOQp0rUkvL+hR0G8fvDM8bAHh51koW7z54GTinQYooPJoqIAmXjc6VLgpzNF07b+bYdXv109H8dUbjIJIZ8L24badJ27ootjYMpNsdUd80ulIGIgEXaibRuq15qRmZg98689s1mPaFxBcGN+eOHHKP79VOYYUh3nClCoxPjKEwQdGjAS80C0emhRbu0=
  file: release/*
  on:
    repo: vitaovich/video-downloader
